### ISSUE TITLE
レベル99到達予想日のレベルを自分で決めたい(機能追加要望)

### ISSUE THREAD

**Issue by mimikun** [muziyoshiz/admiral_stats#11]
今はレベル30, 50, 70, 90, 99の5つだけですが、自分で細かく決めたいので、自分で到達レベルを設定できるような機能が欲しいです。

**Comment by muziyoshiz** [comment]
私自身はあまり不便を感じていないので、すぐにはいいUIが思いつかなそうです。
ちょっと考えてみます。

**Comment by mimikun** [comment]
分かりました。ありがとうございます

提案ですが、このような設定画面で設定した値をもとに表示する感じなら
既存のコードを使えそうなので良いのでは無いか？と思いました。
<img width="503" alt="2017-06-27 19 39 30" src="https://user-images.githubusercontent.com/13450321/27583955-2bb484ea-5b71-11e7-85cb-3584bbd2722d.png">

**Comment by muziyoshiz** [comment]
アイディアありがとうございます。どういう機能をイメージしているか伝わりました。
